SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBMATRICULA;
CREATE DATABASE DBMATRICULA;
USE DBMATRICULA;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(45)
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE DISCIPLINA(	
	IDDISCIPLINA INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(45)
	, DT_INICIO DATE
	, DT_FIM DATE
    , PRIMARY KEY (IDDISCIPLINA)
);

CREATE TABLE MATRICULA (
	IDMATRICULA INT NOT NULL AUTO_INCREMENT
	, IDALUNO INT NOT NULL
    , IDDISCIPLINA INT NOT NULL
	, DT_MATRICULA DATE
    , PRIMARY KEY (IDMATRICULA)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
    , FOREIGN KEY (IDDISCIPLINA) REFERENCES DISCIPLINA (IDDISCIPLINA)
);