DROP DATABASE IF EXISTS DBIMPOSTO;
CREATE DATABASE DBIMPOSTO;
USE DBIMPOSTO;

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(45)
	, ESTADO CHAR(2)
	, VALOR NUMERIC(8,2)
	, ICMS_PERCENTUAL NUMERIC(8,2)
	, ICMS_VALOR NUMERIC(8,2)
	, PRIMARY KEY(IDPRODUTO)
);

CREATE TABLE BASE_ICMS (
	ESTADO CHAR(2) NOT NULL
	, ICMS_PERCENTUAL NUMERIC(8,2)
	, PRIMARY KEY(ESTADO)
);

INSERT INTO BASE_ICMS VALUES('AC', 17);
INSERT INTO BASE_ICMS VALUES('AL', 18);
INSERT INTO BASE_ICMS VALUES('AM', 18);
INSERT INTO BASE_ICMS VALUES('AP', 18);
INSERT INTO BASE_ICMS VALUES('BA', 18);
INSERT INTO BASE_ICMS VALUES('CE', 18);
INSERT INTO BASE_ICMS VALUES('DF', 18);
INSERT INTO BASE_ICMS VALUES('ES', 17);
INSERT INTO BASE_ICMS VALUES('GO', 17);
INSERT INTO BASE_ICMS VALUES('MA', 18);
INSERT INTO BASE_ICMS VALUES('MT', 17);
INSERT INTO BASE_ICMS VALUES('MS', 17);
INSERT INTO BASE_ICMS VALUES('MG', 18);
INSERT INTO BASE_ICMS VALUES('PA', 17);
INSERT INTO BASE_ICMS VALUES('PB', 18);
INSERT INTO BASE_ICMS VALUES('PR', 18);
INSERT INTO BASE_ICMS VALUES('PE', 18);
INSERT INTO BASE_ICMS VALUES('PI', 18);
INSERT INTO BASE_ICMS VALUES('RN', 18);
INSERT INTO BASE_ICMS VALUES('RS', 18);
INSERT INTO BASE_ICMS VALUES('RJ', 20);
INSERT INTO BASE_ICMS VALUES('RO', 17.5);
INSERT INTO BASE_ICMS VALUES('RR', 17);
INSERT INTO BASE_ICMS VALUES('SC', 17);
INSERT INTO BASE_ICMS VALUES('SP', 18);
INSERT INTO BASE_ICMS VALUES('SE', 18);
INSERT INTO BASE_ICMS VALUES('TO', 18);






